# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icons.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.home_icon = QtWidgets.QPushButton(self.centralwidget)
        self.home_icon.setGeometry(QtCore.QRect(30, 40, 60, 60))
        self.home_icon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_icon.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        # self.home_icon.setText("")
        icon_h = QtGui.QIcon()
        icon_h.addPixmap(QtGui.QPixmap("img/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_icon.setIcon(icon_h)
        self.home_icon.setIconSize(QtCore.QSize(50, 50))
        self.home_icon.setObjectName("home_icon")
        self.menu_icon = QtWidgets.QPushButton(self.centralwidget)
        self.menu_icon.setGeometry(QtCore.QRect(120, 40, 60, 60))
        self.menu_icon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_icon.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        # self.menu_icon.setText("")
        icon_m = QtGui.QIcon()
        icon_m.addPixmap(QtGui.QPixmap("img/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_icon.setIcon(icon_m)
        self.menu_icon.setIconSize(QtCore.QSize(50, 50))
        self.menu_icon.setObjectName("menu_icon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
