#!/usr/bin/env python
# -*- coding: utf-8 -*-
from threading import Thread

# Form implementation generated from reading ui file 'Fast_typeMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from datetime import datetime
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from keyboard import *


class Ui_MainWindow(object):
    def displayTime(self):
        f_temp = datetime.utcfromtimestamp(self.temp).strftime("%M:%S")
        self.time_label_1.setText(f_temp)
        self.temp += 1

    def btn_lrn(self, num):
        self.stackedWidget.setCurrentIndex(2)
        self.num = num
        self.win_lrn()

    def win_lrn(self):
        self.lvl_label.setText(f"Уровень {self.num}")

        self.l = []

        with open(f'levels/level{self.num}.txt', 'r', encoding='utf-8') as f:
            for i in f:
                self.l.append(i)

        self.s = ''.join(self.l)

        th1 = Thread(target=self.start_level_lrn)
        th1.start()

        self.temp = 0
        
        self.inp_1.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.inp_1.setFont(QtGui.QFont("Roboto", 20))
        self.inp_1.setText('Нажмите любую клавишу')

        self.timer.start()

    def start_level_lrn(self):
        key_pressed = read_event()
        if key_pressed.event_type == KEY_DOWN:
            self.inp_1.setText(self.s)
            self.level_lrn()

    def level_lrn(self):
        i = 0
        mist = 0
        while i < len(self.s):
            key = read_event()
            key_name = key.name
            if key.event_type == KEY_UP and (key_name == self.s[i]) or (key_name == 'space' and self.s[i] == ' '):
                i += 1
                text = self.s[i:]
                self.inp_1.setText(text)
                continue
            elif key.event_type == KEY_UP and ((key_name != 'space' and self.s[i - 1] == ' ') or (
                    self.s[i - 1] != ' ' and key_name != self.s[i - 1])):
                mist += 1
        mist -= 1

        self.timer.stop()
        f_temp = datetime.utcfromtimestamp(self.temp - 1).strftime("%M:%S")
        v = round(i / (self.temp - 1) * 60)
        end = 'Ошибки: ' + str(mist) + '   Введено символов: ' + str(i) + '   Время: ' + str(f_temp) + '   Скорость (зн/мин): ' + str(v)
        self.inp_1.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_1.setFont(QtGui.QFont("Roboto", 17))
        self.inp_1.setText(end)
        print('ошибки: ', mist)
        print('введено символов: ', i)
        print('время: ', f_temp)
        print('скорость (зн/мин): ', v)

    def btn_st(self, num):
        self.stackedWidget.setCurrentIndex(2)
        self.num = num
        self.win_st()

    def win_st(self):
        self.lvl_label.setText(f"Уровень {self.num}")

        self.l = []

        with open(f'Stories/Story{self.num}.txt', 'r', encoding='utf-8') as f:
            for i in f:
                self.l.append(i)

        self.s = ''.join(self.l)

        th1 = Thread(target=self.start_level_st)
        th1.start()

        self.temp = 0

        self.inp_1.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.inp_1.setGeometry(QtCore.QRect(180, 130, 911, 150))
        self.inp_1.setFont(QtGui.QFont("Roboto", 20))
        self.inp_1.setText('Нажмите любую клавишу')

        self.timer.start()

    def start_level_st(self):
        key_pressed = read_event()
        if key_pressed.event_type == KEY_DOWN:
            self.inp_1.setText(self.s)
            self.level_st()

    def level_st(self):
        i = 0
        mist = 0
        while i < len(self.s):
            key = read_event()
            key_name = key.name
            if (key.event_type == KEY_UP and (key_name == self.s[i])) or (key_name == 'space' and self.s[i] == ' ') or (key_name == 'enter' and self.s[i] == ''
''):
                i += 1
                text = self.s[i:]
                self.inp_1.setText(text)
                continue
            elif key.event_type == KEY_UP and ((key_name != 'space' and self.s[i - 1] == ' ') or (
                    self.s[i - 1] != ' ' and key_name != self.s[i - 1])):
                mist += 1
        mist -= 1

        self.timer.stop()
        f_temp = datetime.utcfromtimestamp(self.temp - 1).strftime("%M:%S")
        v = round(i / (self.temp - 1) * 60)
        end = 'Ошибки: ' + str(mist) + '   Введено символов: ' + str(i) + '   Время: ' + str(
            f_temp) + '   Скорость (зн/мин): ' + str(v)
        self.inp_1.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_1.setFont(QtGui.QFont("Roboto", 17))
        self.inp_1.setText(end)
        print('ошибки: ', mist)
        print('введено символов: ', i)
        print('время: ', f_temp)
        print('скорость (зн/мин): ', v)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1280, 720)

        self.temp = 0

        self.timer = QtCore.QTimer()
        self.timer.setInterval(1000)
        self.timer.timeout.connect(self.displayTime)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Main = QtWidgets.QWidget()
        self.Main.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Main.setObjectName("Mane")
        self.type = QtWidgets.QLabel(self.Main)
        self.type.setGeometry(QtCore.QRect(670, 70, 321, 131))
        self.type.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                "font: 95pt \"Agency FB\";")
        self.type.setObjectName("type")
        self.Fast = QtWidgets.QLabel(self.Main)
        self.Fast.setGeometry(QtCore.QRect(440, 70, 231, 121))
        self.Fast.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                "font:100pt \"Dancing Script\";\n"
                                "\n"
                                "\n"
                                "\n"
                                "")
        self.Fast.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.Fast.setObjectName("Fast")
        self.lrn = QtWidgets.QPushButton(self.Main)
        self.lrn.setFocusPolicy(Qt.NoFocus)
        self.lrn.setGeometry(QtCore.QRect(270, 350, 340, 120))
        self.lrn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lrn.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 170, 170);\n"
                               "    font: 25pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 27pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 150, 150);       \n"
                               "}")
        self.lrn.setObjectName("lrn")

        self.ex = QtWidgets.QPushButton(self.Main)
        self.ex.setFocusPolicy(Qt.NoFocus)
        self.ex.setGeometry(QtCore.QRect(670, 350, 340, 120))
        self.ex.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ex.setStyleSheet("QPushButton{\n"
                              "    background-color: rgb(255, 203, 185);\n"
                              "    font: 57 20pt \"Montserrat Medium\";\n"
                              "    border-radius: 20px;\n"
                              "}\n"
                              "\n"
                              "QPushButton:hover {\n"
                              "    font-size: 22pt;   \n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed {\n"
                              "    background-color: rgb(229, 182, 166);       \n"
                              "}")
        self.ex.setObjectName("ex")
        self.stackedWidget.addWidget(self.Main)

        self.Learning = QtWidgets.QWidget()
        self.Learning.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Learning.setObjectName("Learning")
        self.label_6 = QtWidgets.QLabel(self.Learning)
        self.label_6.setGeometry(QtCore.QRect(530, 60, 221, 61))
        self.label_6.setStyleSheet("font: 30pt \"Montserrat Medium\";\n"
                                   "background-color:  rgba(188, 255, 199, 0)")
        self.label_6.setObjectName("label_6")

        icon_h = QtGui.QIcon()
        icon_h.addPixmap(QtGui.QPixmap("img/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        icon_m = QtGui.QIcon()
        icon_m.addPixmap(QtGui.QPixmap("img/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.home_icon1 = QtWidgets.QPushButton(self.Learning)
        self.home_icon1.setFocusPolicy(Qt.NoFocus)
        self.home_icon1.setGeometry(QtCore.QRect(30, 40, 60, 60))
        self.home_icon1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_icon1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n")
        self.home_icon1.setIcon(icon_h)
        self.home_icon1.setIconSize(QtCore.QSize(50, 50))
        self.home_icon1.setObjectName("home_icon")
        self.home_icon1.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))

        self.lvl_1 = QtWidgets.QPushButton(self.Learning)
        self.lvl_1.setFocusPolicy(Qt.NoFocus)
        self.lvl_1.setGeometry(QtCore.QRect(70, 180, 241, 121))
        self.lvl_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lvl_1.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_1.setObjectName("lvl_1")
        self.lvl_2 = QtWidgets.QPushButton(self.Learning)
        self.lvl_2.setFocusPolicy(Qt.NoFocus)
        self.lvl_2.setGeometry(QtCore.QRect(370, 180, 241, 121))
        self.lvl_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lvl_2.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_2.setObjectName("lvl_2")
        self.lvl_3 = QtWidgets.QPushButton(self.Learning)
        self.lvl_3.setFocusPolicy(Qt.NoFocus)
        self.lvl_3.setGeometry(QtCore.QRect(670, 180, 241, 121))
        self.lvl_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lvl_3.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_3.setObjectName("lvl_3")
        self.lvl_4 = QtWidgets.QPushButton(self.Learning)
        self.lvl_4.setFocusPolicy(Qt.NoFocus)
        self.lvl_4.setGeometry(QtCore.QRect(970, 180, 241, 121))
        self.lvl_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lvl_4.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}\n"
                                 "")
        self.lvl_4.setObjectName("lvl_4")
        self.lvl_5 = QtWidgets.QPushButton(self.Learning)
        self.lvl_5.setFocusPolicy(Qt.NoFocus)
        self.lvl_5.setGeometry(QtCore.QRect(70, 350, 241, 121))
        self.lvl_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lvl_5.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_5.setObjectName("lvl_5")
        self.lvl_8 = QtWidgets.QPushButton(self.Learning)
        self.lvl_8.setFocusPolicy(Qt.NoFocus)
        self.lvl_8.setGeometry(QtCore.QRect(970, 350, 241, 121))
        self.lvl_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lvl_8.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_8.setObjectName("lvl_8")
        self.lvl_7 = QtWidgets.QPushButton(self.Learning)
        self.lvl_7.setFocusPolicy(Qt.NoFocus)
        self.lvl_7.setGeometry(QtCore.QRect(670, 350, 241, 121))
        self.lvl_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lvl_7.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_7.setObjectName("lvl_7")
        self.lvl_6 = QtWidgets.QPushButton(self.Learning)
        self.lvl_6.setFocusPolicy(Qt.NoFocus)
        self.lvl_6.setGeometry(QtCore.QRect(370, 350, 241, 121))
        self.lvl_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lvl_6.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_6.setObjectName("lvl_6")
        self.lvl_12 = QtWidgets.QPushButton(self.Learning)
        self.lvl_12.setFocusPolicy(Qt.NoFocus)
        self.lvl_12.setGeometry(QtCore.QRect(970, 530, 241, 121))
        self.lvl_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lvl_12.setStyleSheet("QPushButton{\n"
                                  "    background-color: rgb(255, 203, 185);\n"
                                  "    font: 15pt \"Montserrat Medium\";\n"
                                  "    border-radius: 20px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover {\n"
                                  "    font-size: 17pt;   \n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "    background-color: rgb(229, 182, 166);       \n"
                                  "}")
        self.lvl_12.setObjectName("lvl_12")
        self.lvl_9 = QtWidgets.QPushButton(self.Learning)
        self.lvl_9.setFocusPolicy(Qt.NoFocus)
        self.lvl_9.setGeometry(QtCore.QRect(70, 530, 241, 121))
        self.lvl_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lvl_9.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_9.setObjectName("lvl_9")
        self.lvl_10 = QtWidgets.QPushButton(self.Learning)
        self.lvl_10.setFocusPolicy(Qt.NoFocus)
        self.lvl_10.setGeometry(QtCore.QRect(370, 530, 241, 121))
        self.lvl_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lvl_10.setStyleSheet("QPushButton{\n"
                                  "    background-color: rgb(255, 203, 185);\n"
                                  "    font: 15pt \"Montserrat Medium\";\n"
                                  "    border-radius: 20px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover {\n"
                                  "    font-size: 17pt;   \n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "    background-color: rgb(229, 182, 166);       \n"
                                  "}")
        self.lvl_10.setObjectName("lvl_10")
        self.lvl_11 = QtWidgets.QPushButton(self.Learning)
        self.lvl_11.setFocusPolicy(Qt.NoFocus)
        self.lvl_11.setGeometry(QtCore.QRect(670, 530, 241, 121))
        self.lvl_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lvl_11.setStyleSheet("QPushButton{\n"
                                  "    background-color: rgb(255, 203, 185);\n"
                                  "    font: 15pt \"Montserrat Medium\";\n"
                                  "    border-radius: 20px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover {\n"
                                  "    font-size: 17pt;   \n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "    background-color: rgb(229, 182, 166);       \n"
                                  "}")
        self.lvl_11.setObjectName("lvl_11")
        self.stackedWidget.addWidget(self.Learning)

        self.Levels = QtWidgets.QWidget()
        self.Levels.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Levels.setObjectName("Levels")

        self.home_icon2 = QtWidgets.QPushButton(self.Levels)
        self.home_icon2.setFocusPolicy(Qt.NoFocus)
        self.home_icon2.setGeometry(QtCore.QRect(30, 40, 60, 60))
        self.home_icon2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_icon2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n""")
        self.home_icon2.setIcon(icon_h)
        self.home_icon2.setIconSize(QtCore.QSize(50, 50))
        self.home_icon2.setObjectName("home_icon")
        self.home_icon2.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))

        self.menu_icon_lvl = QtWidgets.QPushButton(self.Levels)
        self.menu_icon_lvl.setFocusPolicy(Qt.NoFocus)
        self.menu_icon_lvl.setGeometry(QtCore.QRect(120, 40, 60, 60))
        self.menu_icon_lvl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_icon_lvl.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n")
        self.menu_icon_lvl.setIcon(icon_m)
        self.menu_icon_lvl.setIconSize(QtCore.QSize(50, 50))
        self.menu_icon_lvl.setObjectName("menu_icon")
        self.menu_icon_lvl.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))

        self.let1_1 = QtWidgets.QLabel(self.Levels)
        self.let1_1.setGeometry(QtCore.QRect(190, 320, 51, 51))
        self.let1_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_1.setAutoFillBackground(False)
        self.let1_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
                                  "font: 15pt \"Roboto\";\n"
                                  "border-radius: 5px;\n"
                                  "border: 1px solid rgb(100, 100, 100);")
        self.let1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_1.setObjectName("let1_1")

        self.n1_1 = QtWidgets.QLabel(self.Levels)
        self.n1_1.setGeometry(QtCore.QRect(250, 320, 51, 51))
        self.n1_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n1_1.setAutoFillBackground(False)
        self.n1_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
                                "font: 15pt \"Roboto\";\n"
                                "border-radius: 5px;\n"
                                "border: 1px solid rgb(0, 0, 0);\n"
                                "border: 1px solid rgb(100, 100, 100);")
        self.n1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.n1_1.setObjectName("n1_1")

        self.n2_1 = QtWidgets.QLabel(self.Levels)
        self.n2_1.setGeometry(QtCore.QRect(310, 320, 51, 51))
        self.n2_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n2_1.setAutoFillBackground(False)
        self.n2_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
                                "font: 15pt \"Roboto\";\n"
                                "border-radius: 5px;\n"
                                "border: 1px solid rgb(100, 100, 100);")
        self.n2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.n2_1.setObjectName("n2_1")

        self.n3_1 = QtWidgets.QLabel(self.Levels)
        self.n3_1.setGeometry(QtCore.QRect(370, 320, 51, 51))
        self.n3_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n3_1.setAutoFillBackground(False)
        self.n3_1.setStyleSheet("background-color: rgb(226, 224, 173);\n"
                                "font: 15pt \"Roboto\";\n"
                                "border-radius: 5px;\n"
                                "border: 1px solid rgb(100, 100, 100);")
        self.n3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.n3_1.setObjectName("n3_1")

        self.n4_1 = QtWidgets.QLabel(self.Levels)
        self.n4_1.setGeometry(QtCore.QRect(430, 320, 51, 51))
        self.n4_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n4_1.setAutoFillBackground(False)
        self.n4_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                "font: 15pt \"Roboto\";\n"
                                "border-radius: 5px;\n"
                                "border: 1px solid rgb(100, 100, 100);")
        self.n4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.n4_1.setObjectName("n4_1")

        self.n5_1 = QtWidgets.QLabel(self.Levels)
        self.n5_1.setGeometry(QtCore.QRect(490, 320, 51, 51))
        self.n5_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n5_1.setAutoFillBackground(False)
        self.n5_1.setStyleSheet("background-color: rgb(173, 226, 222);\n"
                                "font: 15pt \"Roboto\";\n"
                                "border-radius: 5px;\n"
                                "border: 1px solid rgb(100, 100, 100);")
        self.n5_1.setAlignment(QtCore.Qt.AlignCenter)
        self.n5_1.setObjectName("n5_1")

        self.n6_1 = QtWidgets.QLabel(self.Levels)
        self.n6_1.setGeometry(QtCore.QRect(550, 320, 51, 51))
        self.n6_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n6_1.setAutoFillBackground(False)
        self.n6_1.setStyleSheet("background-color: rgb(173, 226, 222);\n"
                                "font: 15pt \"Roboto\";\n"
                                "border-radius: 5px;\n"
                                "border: 1px solid rgb(100, 100, 100);")
        self.n6_1.setAlignment(QtCore.Qt.AlignCenter)
        self.n6_1.setObjectName("n6_1")

        self.n7_1 = QtWidgets.QLabel(self.Levels)
        self.n7_1.setGeometry(QtCore.QRect(610, 320, 51, 51))
        self.n7_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n7_1.setAutoFillBackground(False)
        self.n7_1.setStyleSheet("background-color: rgb(223, 173, 226);\n"
                                "font: 15pt \"Roboto\";\n"
                                "border-radius: 5px;\n"
                                "border: 1px solid rgb(100, 100, 100);")
        self.n7_1.setAlignment(QtCore.Qt.AlignCenter)
        self.n7_1.setObjectName("n7_1")

        self.n8_1 = QtWidgets.QLabel(self.Levels)
        self.n8_1.setGeometry(QtCore.QRect(670, 320, 51, 51))
        self.n8_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n8_1.setAutoFillBackground(False)
        self.n8_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
                                "font: 15pt \"Roboto\";\n"
                                "border-radius: 5px;\n"
                                "border: 1px solid rgb(100, 100, 100);")
        self.n8_1.setAlignment(QtCore.Qt.AlignCenter)
        self.n8_1.setObjectName("n8_1")

        self.n9_1 = QtWidgets.QLabel(self.Levels)
        self.n9_1.setGeometry(QtCore.QRect(730, 320, 51, 51))
        self.n9_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n9_1.setAutoFillBackground(False)
        self.n9_1.setStyleSheet("background-color: rgb(226, 224, 173);\n"
                                "font: 15pt \"Roboto\";\n"
                                "border-radius: 5px;\n"
                                "border: 1px solid rgb(100, 100, 100);")
        self.n9_1.setAlignment(QtCore.Qt.AlignCenter)
        self.n9_1.setObjectName("n9_1")

        self.n0_1 = QtWidgets.QLabel(self.Levels)
        self.n0_1.setGeometry(QtCore.QRect(790, 320, 51, 51))
        self.n0_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n0_1.setAutoFillBackground(False)
        self.n0_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                "font: 15pt \"Roboto\";\n"
                                "border-radius: 5px;\n"
                                "border: 1px solid rgb(100, 100, 100);")
        self.n0_1.setAlignment(QtCore.Qt.AlignCenter)
        self.n0_1.setObjectName("n0_1")

        self.dash_1 = QtWidgets.QLabel(self.Levels)
        self.dash_1.setGeometry(QtCore.QRect(850, 320, 51, 51))
        self.dash_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dash_1.setAutoFillBackground(False)
        self.dash_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                  "font: 15pt \"Roboto\";\n"
                                  "border-radius: 5px;\n"
                                  "border: 1px solid rgb(100, 100, 100);")
        self.dash_1.setAlignment(QtCore.Qt.AlignCenter)
        self.dash_1.setObjectName("dash_1")

        self.eq_1 = QtWidgets.QLabel(self.Levels)
        self.eq_1.setGeometry(QtCore.QRect(910, 320, 51, 51))
        self.eq_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.eq_1.setAutoFillBackground(False)
        self.eq_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                "font: 15pt \"Roboto\";\n"
                                "border-radius: 5px;\n"
                                "border: 1px solid rgb(100, 100, 100);")
        self.eq_1.setAlignment(QtCore.Qt.AlignCenter)
        self.eq_1.setObjectName("eq_1")

        self.backspace_1 = QtWidgets.QLabel(self.Levels)
        self.backspace_1.setGeometry(QtCore.QRect(970, 320, 111, 51))
        self.backspace_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.backspace_1.setAutoFillBackground(False)
        self.backspace_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                       "color: rgb(50, 50, 50);\n"
                                       "font: 8pt \"Roboto\";\n"
                                       "border-radius: 5px;\n"
                                       "border: 1px solid rgb(100, 100, 100);")
        self.backspace_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.backspace_1.setIndent(10)
        self.backspace_1.setObjectName("backspace_1")

        self.tab_1 = QtWidgets.QLabel(self.Levels)
        self.tab_1.setGeometry(QtCore.QRect(190, 380, 71, 51))
        self.tab_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_1.setAutoFillBackground(False)
        self.tab_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                 "color: rgb(50, 50, 50);\n"
                                 "font: 8pt \"Roboto\";\n"
                                 "border-radius: 5px;\n"
                                 "border: 1px solid rgb(100, 100, 100);")
        self.tab_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.tab_1.setObjectName("tab_1")
        self.tab_1.setIndent(5)

        self.let2_1 = QtWidgets.QLabel(self.Levels)
        self.let2_1.setGeometry(QtCore.QRect(270, 380, 51, 51))
        self.let2_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_1.setAutoFillBackground(False)
        self.let2_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
                                  "font: 15pt \"Roboto\";\n"
                                  "border-radius: 5px;\n"
                                  "border: 1px solid rgb(100, 100, 100);")
        self.let2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_1.setObjectName("let2_1")

        self.let3_1 = QtWidgets.QLabel(self.Levels)
        self.let3_1.setGeometry(QtCore.QRect(330, 380, 51, 51))
        self.let3_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_1.setAutoFillBackground(False)
        self.let3_1.setStyleSheet("background-color: rgb(226, 224, 173);\n"
                                  "font: 15pt \"Roboto\";\n"
                                  "border-radius: 5px;\n"
                                  "border: 1px solid rgb(100, 100, 100);")
        self.let3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_1.setObjectName("let3_1")

        self.let4_1 = QtWidgets.QLabel(self.Levels)
        self.let4_1.setGeometry(QtCore.QRect(390, 380, 51, 51))
        self.let4_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let4_1.setAutoFillBackground(False)
        self.let4_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                  "font: 15pt \"Roboto\";\n"
                                  "border-radius: 5px;\n"
                                  "border: 1px solid rgb(100, 100, 100);")
        self.let4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let4_1.setObjectName("let4_1")

        self.let5_1 = QtWidgets.QLabel(self.Levels)
        self.let5_1.setGeometry(QtCore.QRect(450, 380, 51, 51))
        self.let5_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let5_1.setAutoFillBackground(False)
        self.let5_1.setStyleSheet("background-color: rgb(173, 226, 222);\n"
                                  "font: 15pt \"Roboto\";\n"
                                  "border-radius: 5px;\n"
                                  "border: 1px solid rgb(100, 100, 100);")
        self.let5_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let5_1.setObjectName("let5_1")

        self.let6_1 = QtWidgets.QLabel(self.Levels)
        self.let6_1.setGeometry(QtCore.QRect(510, 380, 51, 51))
        self.let6_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let6_1.setAutoFillBackground(False)
        self.let6_1.setStyleSheet("background-color: rgb(173, 226, 222);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let6_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let6_1.setObjectName("let6_1")

        self.let7_1 = QtWidgets.QLabel(self.Levels)
        self.let7_1.setGeometry(QtCore.QRect(570, 380, 51, 51))
        self.let7_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let7_1.setAutoFillBackground(False)
        self.let7_1.setStyleSheet("background-color: rgb(223, 173, 226);\n"
                                  "font: 15pt \"Roboto\";\n"
                                  "border-radius: 5px;\n"
                                  "border: 1px solid rgb(100, 100, 100);")
        self.let7_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let7_1.setObjectName("let7_1")

        self.let8_1 = QtWidgets.QLabel(self.Levels)
        self.let8_1.setGeometry(QtCore.QRect(630, 380, 51, 51))
        self.let8_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let8_1.setAutoFillBackground(False)
        self.let8_1.setStyleSheet("background-color: rgb(223, 173, 226);\n"
                                  "font: 15pt \"Roboto\";\n"
                                  "border-radius: 5px;\n"
                                  "border: 1px solid rgb(100, 100, 100);")
        self.let8_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let8_1.setObjectName("let8_1")

        self.let9_1 = QtWidgets.QLabel(self.Levels)
        self.let9_1.setGeometry(QtCore.QRect(690, 380, 51, 51))
        self.let9_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let9_1.setAutoFillBackground(False)
        self.let9_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
                                  "font: 15pt \"Roboto\";\n"
                                  "border-radius: 5px;\n"
                                  "border: 1px solid rgb(100, 100, 100);")
        self.let9_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let9_1.setObjectName("let9_1")

        self.let10_1 = QtWidgets.QLabel(self.Levels)
        self.let10_1.setGeometry(QtCore.QRect(750, 380, 51, 51))
        self.let10_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let10_1.setAutoFillBackground(False)
        self.let10_1.setStyleSheet("background-color: rgb(226, 224, 173);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let10_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let10_1.setObjectName("let10_1")

        self.let11_1 = QtWidgets.QLabel(self.Levels)
        self.let11_1.setGeometry(QtCore.QRect(810, 380, 51, 51))
        self.let11_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let11_1.setAutoFillBackground(False)
        self.let11_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let11_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let11_1.setObjectName("let11_1")

        self.let12_1 = QtWidgets.QLabel(self.Levels)
        self.let12_1.setGeometry(QtCore.QRect(870, 380, 51, 51))
        self.let12_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let12_1.setAutoFillBackground(False)
        self.let12_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let12_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let12_1.setObjectName("let12_1")

        self.let13_1 = QtWidgets.QLabel(self.Levels)
        self.let13_1.setGeometry(QtCore.QRect(930, 380, 51, 51))
        self.let13_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let13_1.setAutoFillBackground(False)
        self.let13_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let13_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let13_1.setObjectName("let13_1")

        self.slash_1 = QtWidgets.QLabel(self.Levels)
        self.slash_1.setGeometry(QtCore.QRect(990, 380, 91, 51))
        self.slash_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slash_1.setAutoFillBackground(False)
        self.slash_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.slash_1.setAlignment(QtCore.Qt.AlignCenter)
        self.slash_1.setObjectName("slash_1")

        self.caps_1 = QtWidgets.QLabel(self.Levels)
        self.caps_1.setGeometry(QtCore.QRect(190, 440, 101, 51))
        self.caps_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.caps_1.setAutoFillBackground(False)
        self.caps_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                  "color: rgb(50, 50, 50);\n"
                                  "font: 8pt \"Roboto\";\n"
                                  "border-radius: 5px;\n"
                                  "border: 1px solid rgb(100, 100, 100);")
        self.caps_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.caps_1.setIndent(10)
        self.caps_1.setObjectName("caps_1")

        self.let14_1 = QtWidgets.QLabel(self.Levels)
        self.let14_1.setGeometry(QtCore.QRect(300, 440, 51, 51))
        self.let14_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let14_1.setAutoFillBackground(False)
        self.let14_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let14_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let14_1.setObjectName("let14_1")

        self.let15_1 = QtWidgets.QLabel(self.Levels)
        self.let15_1.setGeometry(QtCore.QRect(360, 440, 51, 51))
        self.let15_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let15_1.setAutoFillBackground(False)
        self.let15_1.setStyleSheet("background-color: rgb(226, 224, 173);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let15_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let15_1.setObjectName("let15_1")

        self.let16_1 = QtWidgets.QLabel(self.Levels)
        self.let16_1.setGeometry(QtCore.QRect(420, 440, 51, 51))
        self.let16_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let16_1.setAutoFillBackground(False)
        self.let16_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let16_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let16_1.setObjectName("let16_1")

        self.let17_1 = QtWidgets.QLabel(self.Levels)
        self.let17_1.setGeometry(QtCore.QRect(480, 440, 51, 51))
        self.let17_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let17_1.setAutoFillBackground(False)
        self.let17_1.setStyleSheet("background-color: rgb(173, 226, 222);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let17_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let17_1.setObjectName("let17_1")

        self.let18_1 = QtWidgets.QLabel(self.Levels)
        self.let18_1.setGeometry(QtCore.QRect(540, 440, 51, 51))
        self.let18_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let18_1.setAutoFillBackground(False)
        self.let18_1.setStyleSheet("background-color: rgb(173, 226, 222);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let18_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let18_1.setObjectName("let18_1")

        self.let19_1 = QtWidgets.QLabel(self.Levels)
        self.let19_1.setGeometry(QtCore.QRect(600, 440, 51, 51))
        self.let19_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let19_1.setAutoFillBackground(False)
        self.let19_1.setStyleSheet("background-color: rgb(223, 173, 226);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let19_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let19_1.setObjectName("let19_1")

        self.let20_1 = QtWidgets.QLabel(self.Levels)
        self.let20_1.setGeometry(QtCore.QRect(660, 440, 51, 51))
        self.let20_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let20_1.setAutoFillBackground(False)
        self.let20_1.setStyleSheet("background-color: rgb(223, 173, 226);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let20_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let20_1.setObjectName("let20_1")

        self.let21_1 = QtWidgets.QLabel(self.Levels)
        self.let21_1.setGeometry(QtCore.QRect(720, 440, 51, 51))
        self.let21_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let21_1.setAutoFillBackground(False)
        self.let21_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let21_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let21_1.setObjectName("let21_1")

        self.let22_1 = QtWidgets.QLabel(self.Levels)
        self.let22_1.setGeometry(QtCore.QRect(780, 440, 51, 51))
        self.let22_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let22_1.setAutoFillBackground(False)
        self.let22_1.setStyleSheet("background-color: rgb(226, 224, 173);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let22_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let22_1.setObjectName("let22_1")

        self.let23_1 = QtWidgets.QLabel(self.Levels)
        self.let23_1.setGeometry(QtCore.QRect(840, 440, 51, 51))
        self.let23_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let23_1.setAutoFillBackground(False)
        self.let23_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let23_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let23_1.setObjectName("let23_1")

        self.let24_1 = QtWidgets.QLabel(self.Levels)
        self.let24_1.setGeometry(QtCore.QRect(900, 440, 51, 51))
        self.let24_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let24_1.setAutoFillBackground(False)
        self.let24_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let24_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let24_1.setObjectName("let24_1")

        self.enter_1 = QtWidgets.QLabel(self.Levels)
        self.enter_1.setGeometry(QtCore.QRect(960, 440, 121, 51))
        self.enter_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enter_1.setAutoFillBackground(False)
        self.enter_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                   "color: rgb(50, 50, 50);\n"
                                   "font: 8pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.enter_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.enter_1.setIndent(10)
        self.enter_1.setObjectName("enter_1")

        self.l_shift_1 = QtWidgets.QLabel(self.Levels)
        self.l_shift_1.setGeometry(QtCore.QRect(190, 500, 141, 51))
        self.l_shift_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_shift_1.setAutoFillBackground(False)
        self.l_shift_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                     "color: rgb(50, 50, 50);\n"
                                     "font: 8pt \"Roboto\";\n"
                                     "border-radius: 5px;\n"
                                     "border: 1px solid rgb(100, 100, 100);")
        self.l_shift_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.l_shift_1.setIndent(10)
        self.l_shift_1.setObjectName("l_shift_1")

        self.let25_1 = QtWidgets.QLabel(self.Levels)
        self.let25_1.setGeometry(QtCore.QRect(340, 500, 51, 51))
        self.let25_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let25_1.setAutoFillBackground(False)
        self.let25_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let25_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let25_1.setObjectName("let25_1")

        self.let26_1 = QtWidgets.QLabel(self.Levels)
        self.let26_1.setGeometry(QtCore.QRect(400, 500, 51, 51))
        self.let26_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let26_1.setAutoFillBackground(False)
        self.let26_1.setStyleSheet("background-color: rgb(226, 224, 173);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let26_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let26_1.setObjectName("let26_1")

        self.let27_1 = QtWidgets.QLabel(self.Levels)
        self.let27_1.setGeometry(QtCore.QRect(460, 500, 51, 51))
        self.let27_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let27_1.setAutoFillBackground(False)
        self.let27_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let27_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let27_1.setObjectName("let27_1")

        self.let28_1 = QtWidgets.QLabel(self.Levels)
        self.let28_1.setGeometry(QtCore.QRect(520, 500, 51, 51))
        self.let28_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let28_1.setAutoFillBackground(False)
        self.let28_1.setStyleSheet("background-color: rgb(173, 226, 222);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let28_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let28_1.setObjectName("let28_1")

        self.let29_1 = QtWidgets.QLabel(self.Levels)
        self.let29_1.setGeometry(QtCore.QRect(580, 500, 51, 51))
        self.let29_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let29_1.setAutoFillBackground(False)
        self.let29_1.setStyleSheet("background-color: rgb(173, 226, 222);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let29_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let29_1.setObjectName("let29_1")

        self.let30_1 = QtWidgets.QLabel(self.Levels)
        self.let30_1.setGeometry(QtCore.QRect(640, 500, 51, 51))
        self.let30_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let30_1.setAutoFillBackground(False)
        self.let30_1.setStyleSheet("background-color: rgb(223, 173, 226);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let30_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let30_1.setObjectName("let30_1")

        self.let31_1 = QtWidgets.QLabel(self.Levels)
        self.let31_1.setGeometry(QtCore.QRect(700, 500, 51, 51))
        self.let31_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let31_1.setAutoFillBackground(False)
        self.let31_1.setStyleSheet("background-color: rgb(223, 173, 226);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let31_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let31_1.setObjectName("let31_1")

        self.let32_1 = QtWidgets.QLabel(self.Levels)
        self.let32_1.setGeometry(QtCore.QRect(760, 500, 51, 51))
        self.let32_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let32_1.setAutoFillBackground(False)
        self.let32_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let32_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let32_1.setObjectName("let32_1")

        self.let33_1 = QtWidgets.QLabel(self.Levels)
        self.let33_1.setGeometry(QtCore.QRect(820, 500, 51, 51))
        self.let33_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let33_1.setAutoFillBackground(False)
        self.let33_1.setStyleSheet("background-color: rgb(226, 224, 173);\n"
                                   "font: 15pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.let33_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let33_1.setObjectName("let33_1")

        self.dot_1 = QtWidgets.QLabel(self.Levels)
        self.dot_1.setGeometry(QtCore.QRect(880, 500, 51, 51))
        self.dot_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dot_1.setAutoFillBackground(False)
        self.dot_1.setStyleSheet("background-color: rgb(173, 227, 176);\n"
                                 "font: 15pt \"Roboto\";\n"
                                 "border-radius: 5px;\n"
                                 "border: 1px solid rgb(100, 100, 100);")
        self.dot_1.setAlignment(QtCore.Qt.AlignCenter)
        self.dot_1.setObjectName("dot_1")

        self.r_shift_1 = QtWidgets.QLabel(self.Levels)
        self.r_shift_1.setGeometry(QtCore.QRect(940, 500, 141, 51))
        self.r_shift_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.r_shift_1.setAutoFillBackground(False)
        self.r_shift_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                     "color: rgb(50, 50, 50);\n"
                                     "font: 8pt \"Roboto\";\n"
                                     "border-radius: 5px;\n"
                                     "border: 1px solid rgb(100, 100, 100);")
        self.r_shift_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.r_shift_1.setIndent(10)
        self.r_shift_1.setObjectName("r_shift_1")

        self.l_ctrl_1 = QtWidgets.QLabel(self.Levels)
        self.l_ctrl_1.setGeometry(QtCore.QRect(190, 560, 61, 51))
        self.l_ctrl_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_ctrl_1.setAutoFillBackground(False)
        self.l_ctrl_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                    "color: rgb(50, 50, 50);\n"
                                    "font: 8pt \"Roboto\";\n"
                                    "border-radius: 5px;\n"
                                    "border: 1px solid rgb(100, 100, 100);")
        self.l_ctrl_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_ctrl_1.setObjectName("l_ctrl_1")

        self.l_win_1 = QtWidgets.QLabel(self.Levels)
        self.l_win_1.setGeometry(QtCore.QRect(270, 560, 61, 51))
        self.l_win_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_win_1.setAutoFillBackground(False)
        self.l_win_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                   "color: rgb(50, 50, 50);\n"
                                   "font: 8pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.l_win_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_win_1.setObjectName("l_win_1")

        self.l_alt_1 = QtWidgets.QLabel(self.Levels)
        self.l_alt_1.setGeometry(QtCore.QRect(340, 560, 61, 51))
        self.l_alt_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_alt_1.setAutoFillBackground(False)
        self.l_alt_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                   "color: rgb(50, 50, 50);\n"
                                   "font: 8pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.l_alt_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_alt_1.setObjectName("l_alt_1")

        self.space_1 = QtWidgets.QLabel(self.Levels)
        self.space_1.setGeometry(QtCore.QRect(410, 560, 391, 51))
        self.space_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.space_1.setAutoFillBackground(False)
        self.space_1.setStyleSheet("background-color: rgb(175, 175, 225);\n"
                                   "font: 10pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.space_1.setText("")
        self.space_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.space_1.setObjectName("space_1")

        self.r_alt_1 = QtWidgets.QLabel(self.Levels)
        self.r_alt_1.setGeometry(QtCore.QRect(810, 560, 61, 51))
        self.r_alt_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.r_alt_1.setAutoFillBackground(False)
        self.r_alt_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                   "color: rgb(50, 50, 50);\n"
                                   "font: 8pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.r_alt_1.setAlignment(QtCore.Qt.AlignCenter)
        self.r_alt_1.setObjectName("r_alt_1")

        self.r_win_1 = QtWidgets.QLabel(self.Levels)
        self.r_win_1.setGeometry(QtCore.QRect(880, 560, 61, 51))
        self.r_win_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.r_win_1.setAutoFillBackground(False)
        self.r_win_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                   "color: rgb(50, 50, 50);\n"
                                   "font: 8pt \"Roboto\";\n"
                                   "border-radius: 5px;\n"
                                   "border: 1px solid rgb(100, 100, 100);")
        self.r_win_1.setAlignment(QtCore.Qt.AlignCenter)
        self.r_win_1.setObjectName("r_win_1")

        self.menu_1 = QtWidgets.QLabel(self.Levels)
        self.menu_1.setGeometry(QtCore.QRect(950, 560, 61, 51))
        self.menu_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu_1.setAutoFillBackground(False)
        self.menu_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                  "color: rgb(50, 50, 50);\n"
                                  "font: 8pt \"Roboto\";\n"
                                  "border-radius: 5px;\n"
                                  "border: 1px solid rgb(100, 100, 100);")
        self.menu_1.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_1.setObjectName("menu_1")

        self.r_ctrl_1 = QtWidgets.QLabel(self.Levels)
        self.r_ctrl_1.setGeometry(QtCore.QRect(1020, 560, 61, 51))
        self.r_ctrl_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.r_ctrl_1.setAutoFillBackground(False)
        self.r_ctrl_1.setStyleSheet("background-color: rgb(215, 215, 215);\n"
                                    "color: rgb(50, 50, 50);\n"
                                    "font: 8pt \"Roboto\";\n"
                                    "border-radius: 5px;\n"
                                    "border: 1px solid rgb(100, 100, 100);")
        self.r_ctrl_1.setAlignment(QtCore.Qt.AlignCenter)
        self.r_ctrl_1.setObjectName("r_ctrl_1")

        self.lvl_label = QtWidgets.QLabel(self.Levels)
        self.lvl_label.setGeometry(QtCore.QRect(-20, -10, 121, 41))
        self.lvl_label.setStyleSheet("background-color: rgba(188, 255, 199, 255);\n"
                                 "background-color: rgb(156, 212, 165);\n"
                                 "font: 10pt \"Montserrat Medium\";\n"
                                 "border-radius: 10px;")
        self.lvl_label.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lvl_label.setIndent(5)
        self.lvl_label.setObjectName("lvl_label")

        self.inp_1 = QtWidgets.QLabel(self.Levels)
        self.inp_1.setGeometry(QtCore.QRect(180, 180, 911, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.inp_1.setFont(font)
        self.inp_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inp_1.setObjectName("inp_1")
        self.inp_1.setIndent(50)

        self.bg_1 = QtWidgets.QLabel(self.Levels)
        self.bg_1.setGeometry(QtCore.QRect(170, 300, 931, 331))
        self.bg_1.setStyleSheet("background-color: rgb(153, 180, 209);\n"
                                "border-radius: 5px;")
        self.bg_1.setText("")
        self.bg_1.setObjectName("bg_1")

        self.time_label_1 = QtWidgets.QLabel(self.Levels)
        self.time_label_1.setGeometry(QtCore.QRect(600, 70, 91, 41))
        self.time_label_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "border-radius: 10px;\n"
                                      "font: 15pt \"Roboto\";")
        self.time_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label_1.setObjectName("time_label_1")

        self.home_icon1.raise_()
        self.home_icon2.raise_()

        self.lvl_label.raise_()
        self.bg_1.raise_()
        self.time_label_1.raise_()

        self.inp_1.raise_()

        self.let1_1.raise_()
        self.n1_1.raise_()
        self.n2_1.raise_()
        self.n3_1.raise_()
        self.n4_1.raise_()
        self.n5_1.raise_()
        self.n6_1.raise_()
        self.n7_1.raise_()
        self.n9_1.raise_()
        self.n8_1.raise_()
        self.n0_1.raise_()
        self.dash_1.raise_()
        self.eq_1.raise_()
        self.backspace_1.raise_()

        self.tab_1.raise_()
        self.let2_1.raise_()
        self.let3_1.raise_()
        self.let4_1.raise_()
        self.let5_1.raise_()
        self.let6_1.raise_()
        self.let7_1.raise_()
        self.let8_1.raise_()
        self.let9_1.raise_()
        self.let10_1.raise_()
        self.let11_1.raise_()
        self.let12_1.raise_()
        self.let13_1.raise_()
        self.slash_1.raise_()

        self.caps_1.raise_()
        self.let14_1.raise_()
        self.let15_1.raise_()
        self.let16_1.raise_()
        self.let17_1.raise_()
        self.let18_1.raise_()
        self.let19_1.raise_()
        self.let20_1.raise_()
        self.let21_1.raise_()
        self.let22_1.raise_()
        self.let23_1.raise_()
        self.let24_1.raise_()
        self.enter_1.raise_()

        self.l_shift_1.raise_()
        self.let25_1.raise_()
        self.let26_1.raise_()
        self.let27_1.raise_()
        self.let28_1.raise_()
        self.let29_1.raise_()
        self.let30_1.raise_()
        self.let31_1.raise_()
        self.let32_1.raise_()
        self.let33_1.raise_()
        self.dot_1.raise_()
        self.r_shift_1.raise_()

        self.l_ctrl_1.raise_()
        self.l_win_1.raise_()
        self.l_alt_1.raise_()
        self.space_1.raise_()
        self.r_alt_1.raise_()
        self.r_win_1.raise_()
        self.menu_1.raise_()
        self.r_ctrl_1.raise_()

        self.stackedWidget.addWidget(self.Levels)

        self.Exercise = QtWidgets.QWidget()
        self.Exercise.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Exercise.setObjectName("Exercise")

        self.home_icon3 = QtWidgets.QPushButton(self.Exercise)
        self.home_icon3.setFocusPolicy(Qt.NoFocus)
        self.home_icon3.setGeometry(QtCore.QRect(30, 40, 60, 60))
        self.home_icon3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_icon3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n""")
        self.home_icon3.setIcon(icon_h)
        self.home_icon3.setIconSize(QtCore.QSize(50, 50))
        self.home_icon3.setObjectName("home_icon")
        self.home_icon3.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))

        self.train = QtWidgets.QLabel(self.Exercise)
        self.train.setGeometry(QtCore.QRect(510, 50, 261, 61))
        self.train.setStyleSheet("font: 30pt \"Montserrat Medium\";\n"
                                   "background-color:  rgba(188, 255, 199, 0)")
        self.train.setObjectName("label_8")

        self.time = QtWidgets.QPushButton(self.Exercise)
        self.time.setFocusPolicy(Qt.NoFocus)
        self.time.setGeometry(QtCore.QRect(60, 350, 341, 121))
        self.time.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.time.setStyleSheet("QPushButton{\n"
                                "    background-color: rgb(255, 203, 185);\n"
                                "    font: 15pt \"Montserrat Medium\";\n"
                                "    border-radius: 20px;\n"
                                "}\n"
                                "\n"
                                "QPushButton:hover {\n"
                                "    font-size: 17pt;   \n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed {\n"
                                "    background-color: rgb(229, 182, 166);       \n"
                                "}")
        self.time.setObjectName("time")

        self.story = QtWidgets.QPushButton(self.Exercise)
        self.story.setFocusPolicy(Qt.NoFocus)
        self.story.setGeometry(QtCore.QRect(470, 350, 341, 121))
        self.story.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.story.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.story.setObjectName("story")
        self.hear = QtWidgets.QPushButton(self.Exercise)

        self.hear.setFocusPolicy(Qt.NoFocus)
        self.hear.setGeometry(QtCore.QRect(880, 350, 341, 121))
        self.hear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hear.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 203, 185);\n"
                               "    font: 15pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 17pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 182, 166);       \n"
                               "}")
        self.hear.setObjectName("inf")

        self.stackedWidget.addWidget(self.Exercise)

        self.Stories = QtWidgets.QWidget()
        self.Stories.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Learning.setObjectName("Learning")
        self.label_6 = QtWidgets.QLabel(self.Stories)
        self.label_6.setGeometry(QtCore.QRect(530, 60, 221, 61))
        self.label_6.setStyleSheet("font: 30pt \"Montserrat Medium\";\n"
                                   "background-color:  rgba(188, 255, 199, 0)")
        self.label_6.setObjectName("label_6")

        self.home_icon4 = QtWidgets.QPushButton(self.Stories)
        self.home_icon4.setFocusPolicy(Qt.NoFocus)
        self.home_icon4.setGeometry(QtCore.QRect(30, 40, 60, 60))
        self.home_icon4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_icon4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n")
        self.home_icon4.setIcon(icon_h)
        self.home_icon4.setIconSize(QtCore.QSize(50, 50))
        self.home_icon4.setObjectName("home_icon")
        self.home_icon4.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))

        self.st1 = QtWidgets.QPushButton(self.Stories)
        self.st1.setFocusPolicy(Qt.NoFocus)
        self.st1.setGeometry(QtCore.QRect(60, 200, 220, 150))
        self.st1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.st1.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.st1.setObjectName("st1")

        self.st2 = QtWidgets.QPushButton(self.Stories)
        self.st2.setFocusPolicy(Qt.NoFocus)
        self.st2.setGeometry(QtCore.QRect(295, 200, 220, 150))
        self.st2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.st2.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 203, 185);\n"
                               "    font: 15pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 17pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 182, 166);       \n"
                               "}")
        self.st2.setObjectName("st2")

        self.st3 = QtWidgets.QPushButton(self.Stories)
        self.st3.setFocusPolicy(Qt.NoFocus)
        self.st3.setGeometry(QtCore.QRect(530, 200, 220, 150))
        self.st3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.st3.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 203, 185);\n"
                               "    font: 15pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 17pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 182, 166);       \n"
                               "}")
        self.st3.setObjectName("st3")

        self.st4 = QtWidgets.QPushButton(self.Stories)
        self.st4.setFocusPolicy(Qt.NoFocus)
        self.st4.setGeometry(QtCore.QRect(765, 200, 220, 150))
        self.st4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.st4.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 203, 185);\n"
                               "    font: 15pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 17pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 182, 166);       \n"
                               "}")
        self.st4.setObjectName("st4")

        self.st5 = QtWidgets.QPushButton(self.Stories)
        self.st5.setFocusPolicy(Qt.NoFocus)
        self.st5.setGeometry(QtCore.QRect(1000, 200, 220, 150))
        self.st5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.st5.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 203, 185);\n"
                               "    font: 15pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 17pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 182, 166);       \n"
                               "}")
        self.st5.setObjectName("st5")

        self.st6 = QtWidgets.QPushButton(self.Stories)
        self.st6.setFocusPolicy(Qt.NoFocus)
        self.st6.setGeometry(QtCore.QRect(60, 400, 220, 150))
        self.st6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.st6.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 203, 185);\n"
                               "    font: 15pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 17pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 182, 166);       \n"
                               "}")
        self.st6.setObjectName("st6")

        self.st7 = QtWidgets.QPushButton(self.Stories)
        self.st7.setFocusPolicy(Qt.NoFocus)
        self.st7.setGeometry(QtCore.QRect(295, 400, 220, 150))
        self.st7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.st7.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 203, 185);\n"
                               "    font: 15pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 17pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 182, 166);       \n"
                               "}")
        self.st7.setObjectName("st7")

        self.st8 = QtWidgets.QPushButton(self.Stories)
        self.st8.setFocusPolicy(Qt.NoFocus)
        self.st8.setGeometry(QtCore.QRect(530, 400, 220, 150))
        self.st8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.st8.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 203, 185);\n"
                               "    font: 15pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 17pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 182, 166);       \n"
                               "}")
        self.st8.setObjectName("st8")

        self.st9 = QtWidgets.QPushButton(self.Stories)
        self.st9.setFocusPolicy(Qt.NoFocus)
        self.st9.setGeometry(QtCore.QRect(765, 400, 220, 150))
        self.st9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.st9.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 203, 185);\n"
                               "    font: 15pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 17pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 182, 166);       \n"
                               "}")
        self.st9.setObjectName("st9")

        self.st10 = QtWidgets.QPushButton(self.Stories)
        self.st10.setFocusPolicy(Qt.NoFocus)
        self.st10.setGeometry(QtCore.QRect(1000, 400, 220, 150))
        self.st10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.st10.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 203, 185);\n"
                               "    font: 15pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 17pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 182, 166);       \n"
                               "}")
        self.st10.setObjectName("st10")

        self.stackedWidget.addWidget(self.Stories)

        self.Games = QtWidgets.QWidget()
        self.Games.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Games.setObjectName("Games")

        self.stackedWidget.addWidget(self.Games)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.lrn.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        self.ex.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3))
        self.story.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(4))

        self.lvl_1.clicked.connect(lambda: self.btn_lrn(1))
        self.lvl_2.clicked.connect(lambda: self.btn_lrn(2))
        self.lvl_3.clicked.connect(lambda: self.btn_lrn(3))
        self.lvl_4.clicked.connect(lambda: self.btn_lrn(4))
        self.lvl_5.clicked.connect(lambda: self.btn_lrn(5))
        self.lvl_6.clicked.connect(lambda: self.btn_lrn(6))
        self.lvl_7.clicked.connect(lambda: self.btn_lrn(7))
        self.lvl_8.clicked.connect(lambda: self.btn_lrn(8))
        self.lvl_9.clicked.connect(lambda: self.btn_lrn(9))
        self.lvl_10.clicked.connect(lambda: self.btn_lrn(10))
        self.lvl_11.clicked.connect(lambda: self.btn_lrn(11))
        self.lvl_12.clicked.connect(lambda: self.btn_lrn(12))

        self.st1.clicked.connect(lambda: self.btn_st(1))
        self.st2.clicked.connect(lambda: self.btn_st(2))
        self.st3.clicked.connect(lambda: self.btn_st(3))
        self.st4.clicked.connect(lambda: self.btn_st(4))
        self.st5.clicked.connect(lambda: self.btn_st(5))
        self.st6.clicked.connect(lambda: self.btn_st(6))
        self.st7.clicked.connect(lambda: self.btn_st(7))
        self.st8.clicked.connect(lambda: self.btn_st(8))
        self.st9.clicked.connect(lambda: self.btn_st(9))
        self.st10.clicked.connect(lambda: self.btn_st(10))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fast type"))
        self.type.setText(_translate("MainWindow", "type"))
        self.Fast.setText(_translate("MainWindow", "Fast"))
        self.lrn.setText(_translate("MainWindow", "Обучение"))
        self.ex.setText(_translate("MainWindow", "Тренировка"))
        self.label_6.setText(_translate("MainWindow", "Обучение"))

        self.lvl_1.setText(_translate("MainWindow", "Уровень 1"))
        self.lvl_2.setText(_translate("MainWindow", "Уровень 2"))
        self.lvl_3.setText(_translate("MainWindow", "Уровень 3"))
        self.lvl_4.setText(_translate("MainWindow", "Уровень 4"))
        self.lvl_5.setText(_translate("MainWindow", "Уровень 5"))
        self.lvl_6.setText(_translate("MainWindow", "Уровень 6"))
        self.lvl_7.setText(_translate("MainWindow", "Уровень 7"))
        self.lvl_8.setText(_translate("MainWindow", "Уровень 8"))
        self.lvl_9.setText(_translate("MainWindow", "Уровень 9"))
        self.lvl_10.setText(_translate("MainWindow", "Уровень 10"))
        self.lvl_11.setText(_translate("MainWindow", "Уровень 11"))
        self.lvl_12.setText(_translate("MainWindow", "Уровень 12"))

        self.let1_1.setText(_translate("MainWindow", "ё"))
        self.n1_1.setText(_translate("MainWindow", "1"))
        self.n2_1.setText(_translate("MainWindow", "2"))
        self.n3_1.setText(_translate("MainWindow", "3"))
        self.n4_1.setText(_translate("MainWindow", "4"))
        self.n5_1.setText(_translate("MainWindow", "5"))
        self.n6_1.setText(_translate("MainWindow", "6"))
        self.n7_1.setText(_translate("MainWindow", "7"))
        self.n8_1.setText(_translate("MainWindow", "8"))
        self.n9_1.setText(_translate("MainWindow", "9"))
        self.n0_1.setText(_translate("MainWindow", "0"))
        self.dash_1.setText(_translate("MainWindow", "-"))
        self.eq_1.setText(_translate("MainWindow", "="))
        self.backspace_1.setText(_translate("MainWindow", "Backspace"))

        self.tab_1.setText(_translate("MainWindow", "Tab"))
        self.let2_1.setText(_translate("MainWindow", "й"))
        self.let3_1.setText(_translate("MainWindow", "ц"))
        self.let4_1.setText(_translate("MainWindow", "у"))
        self.let5_1.setText(_translate("MainWindow", "к"))
        self.let6_1.setText(_translate("MainWindow", "е"))
        self.let7_1.setText(_translate("MainWindow", "н"))
        self.let8_1.setText(_translate("MainWindow", "г"))
        self.let9_1.setText(_translate("MainWindow", "ш"))
        self.let10_1.setText(_translate("MainWindow", "щ"))
        self.let11_1.setText(_translate("MainWindow", "з"))
        self.let12_1.setText(_translate("MainWindow", "х"))
        self.let13_1.setText(_translate("MainWindow", "ъ"))
        self.slash_1.setText(_translate("MainWindow", "\\"))

        self.caps_1.setText(_translate("MainWindow", "Caps Lock"))
        self.let14_1.setText(_translate("MainWindow", "ф"))
        self.let15_1.setText(_translate("MainWindow", "ы"))
        self.let16_1.setText(_translate("MainWindow", "в"))
        self.let17_1.setText(_translate("MainWindow", "а"))
        self.let18_1.setText(_translate("MainWindow", "п"))
        self.let19_1.setText(_translate("MainWindow", "р"))
        self.let20_1.setText(_translate("MainWindow", "о"))
        self.let21_1.setText(_translate("MainWindow", "л"))
        self.let22_1.setText(_translate("MainWindow", "д"))
        self.let23_1.setText(_translate("MainWindow", "ж"))
        self.let24_1.setText(_translate("MainWindow", "э"))
        self.enter_1.setText(_translate("MainWindow", "Enter"))

        self.l_shift_1.setText(_translate("MainWindow", "Shift"))
        self.let25_1.setText(_translate("MainWindow", "я"))
        self.let26_1.setText(_translate("MainWindow", "ч"))
        self.let27_1.setText(_translate("MainWindow", "с"))
        self.let28_1.setText(_translate("MainWindow", "м"))
        self.let29_1.setText(_translate("MainWindow", "и"))
        self.let30_1.setText(_translate("MainWindow", "т"))
        self.let31_1.setText(_translate("MainWindow", "ь"))
        self.let32_1.setText(_translate("MainWindow", "б"))
        self.let33_1.setText(_translate("MainWindow", "ю"))
        self.dot_1.setText(_translate("MainWindow", "."))
        self.r_shift_1.setText(_translate("MainWindow", "Shift"))

        self.l_ctrl_1.setText(_translate("MainWindow", "Ctrl"))
        self.l_win_1.setText(_translate("MainWindow", "Win"))
        self.l_alt_1.setText(_translate("MainWindow", "Alt"))
        self.r_alt_1.setText(_translate("MainWindow", "Alt"))
        self.r_win_1.setText(_translate("MainWindow", "Win"))
        self.menu_1.setText(_translate("MainWindow", "Menu"))
        self.r_ctrl_1.setText(_translate("MainWindow", "Ctrl"))

        self.lvl_label.setText(_translate("MainWindow", "Уровень 1"))
        self.time_label_1.setText(_translate("Fast_type", "00:00"))
        self.inp_1.setText(_translate("MainWindow", "Нажмите любую клавишу"))

        self.train.setText(_translate("MainWindow", "Тренировка"))
        self.time.setText(_translate("MainWindow", "На время"))
        self.story.setText(_translate("MainWindow", "Истории"))
        self.hear.setText(_translate("MainWindow", "На слух"))

        self.st1.setText(_translate("MainWindow", "Вверх по лестнице"))
        self.st2.setText(_translate("MainWindow", "Делец"))
        self.st3.setText(_translate("MainWindow", "Неудача"))
        self.st4.setText(_translate("MainWindow", "Дачники"))
        self.st5.setText(_translate("MainWindow", "Баран и барышня"))
        self.st6.setText(_translate("MainWindow", "Толстый и тонкий"))
        self.st7.setText(_translate("MainWindow", "Смерть чиновника"))
        self.st8.setText(_translate("MainWindow", "Пересолил"))
        self.st9.setText(_translate("MainWindow", "Беззаконие"))
        self.st10.setText(_translate("MainWindow", "Визитные карточки"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
