# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Learning.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from datetime import datetime
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *


class Ui_Fast_type(object):
    def setupUi(self, Fast_type):
        self.temp = 0
        Fast_type.setObjectName("Fast_type")
        Fast_type.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(Fast_type)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1280, 730))
        self.stackedWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.stackedWidget.setObjectName("stackedWidget")
        self.lvl_1 = QtWidgets.QWidget()
        self.lvl_1.setObjectName("lvl_1")

        self.label = QtWidgets.QLabel(self.lvl_1)
        self.label.setGeometry(QtCore.QRect(-10, -10, 121, 41))
        self.label.setStyleSheet("background-color: rgba(188, 255, 199, 255);\n"
"background-color: rgb(156, 212, 165);\n"
"font: 10pt \"Montserrat Medium\";\n"
"border-radius: 10px;")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setIndent(5)
        self.label.setObjectName("label")

        self.label_4 = QtWidgets.QLabel(self.lvl_1)
        self.label_4.setGeometry(QtCore.QRect(590, 70, 91, 41))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"font: 15pt \"Roboto\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.button_start1 = QtWidgets.QPushButton(self.lvl_1)
        self.button_start1.setGeometry(QtCore.QRect(700, 75, 100, 30))
        self.button_start1.setObjectName("button_start")
        self.button_start1.clicked.connect(self.func_start)

        self.timer = QtCore.QTimer()
        self.timer.setInterval(1000)
        self.timer.timeout.connect(self.displayTime)

        self.label.raise_()

        self.label_4.raise_()
        self.button_start1.raise_()

        self.stackedWidget.addWidget(self.lvl_1)

        Fast_type.setCentralWidget(self.centralwidget)

        self.retranslateUi(Fast_type)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Fast_type)

    def retranslateUi(self, Fast_type):
        _translate = QtCore.QCoreApplication.translate
        Fast_type.setWindowTitle(_translate("Fast_type", "Fast type"))
        self.label.setText(_translate("Fast_type", "Уровень 1"))

        self.label_4.setText(_translate("Fast_type", "00:00"))
        self.button_start1.setText(_translate("Fast_type", "Старт"))


    def func_start(self):
        if self.button_start1.text() == 'Старт':
            self.timer.start()
            self.button_start1.setText('Стоп')
        else:
            self.timer.stop()
            self.button_start1.setText('Старт')
            self.button_start1.hide()

    def displayTime(self):
        f_temp = datetime.utcfromtimestamp(self.temp).strftime("%M:%S")
        self.label_4.setText(f_temp)
        self.temp += 1


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Fast_type = QtWidgets.QMainWindow()
    ui = Ui_Fast_type()
    ui.setupUi(Fast_type)
    Fast_type.show()
    sys.exit(app.exec_())
