# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fast_typeTime.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(2560, 1440))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(2560, 1440))
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.stackedWidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.stackedWidget.setMaximumSize(QtCore.QSize(2560, 1440))
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Time_beg = QtWidgets.QWidget()
        self.Time_beg.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Time_beg.setObjectName("Time_beg")
        self.stackedWidget.addWidget(self.Time_beg)
        self.Time_mid_2 = QtWidgets.QWidget()
        self.Time_mid_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Time_mid_2.setObjectName("Time_mid_2")
        self.stackedWidget.addWidget(self.Time_mid_2)
        self.Time_pro = QtWidgets.QWidget()
        self.Time_pro.setMinimumSize(QtCore.QSize(1280, 720))
        self.Time_pro.setMaximumSize(QtCore.QSize(2560, 1440))
        self.Time_pro.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Time_pro.setObjectName("Time_pro")
        self.text = QtWidgets.QLabel(self.Time_pro)
        self.text.setGeometry(QtCore.QRect(180, 170, 911, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.text.setFont(font)
        self.text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text.setObjectName("text")
        self.yo = QtWidgets.QLabel(self.Time_pro)
        self.yo.setGeometry(QtCore.QRect(190, 320, 51, 51))
        self.yo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yo.setAutoFillBackground(False)
        self.yo.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.yo.setAlignment(QtCore.Qt.AlignCenter)
        self.yo.setObjectName("yo")
        self.let1_1 = QtWidgets.QLabel(self.Time_pro)
        self.let1_1.setGeometry(QtCore.QRect(270, 380, 51, 51))
        self.let1_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_1.setAutoFillBackground(False)
        self.let1_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_1.setObjectName("let1_1")
        self.n2 = QtWidgets.QLabel(self.Time_pro)
        self.n2.setGeometry(QtCore.QRect(310, 320, 51, 51))
        self.n2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n2.setAutoFillBackground(False)
        self.n2.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n2.setAlignment(QtCore.Qt.AlignCenter)
        self.n2.setObjectName("n2")
        self.n1 = QtWidgets.QLabel(self.Time_pro)
        self.n1.setGeometry(QtCore.QRect(250, 320, 51, 51))
        self.n1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n1.setAutoFillBackground(False)
        self.n1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(0, 0, 0);\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n1.setAlignment(QtCore.Qt.AlignCenter)
        self.n1.setObjectName("n1")
        self.let2_1 = QtWidgets.QLabel(self.Time_pro)
        self.let2_1.setGeometry(QtCore.QRect(300, 440, 51, 51))
        self.let2_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_1.setAutoFillBackground(False)
        self.let2_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_1.setObjectName("let2_1")
        self.let3_1 = QtWidgets.QLabel(self.Time_pro)
        self.let3_1.setGeometry(QtCore.QRect(340, 500, 51, 51))
        self.let3_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_1.setAutoFillBackground(False)
        self.let3_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_1.setObjectName("let3_1")
        self.n3 = QtWidgets.QLabel(self.Time_pro)
        self.n3.setGeometry(QtCore.QRect(370, 320, 51, 51))
        self.n3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n3.setAutoFillBackground(False)
        self.n3.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n3.setAlignment(QtCore.Qt.AlignCenter)
        self.n3.setObjectName("n3")
        self.n5 = QtWidgets.QLabel(self.Time_pro)
        self.n5.setGeometry(QtCore.QRect(490, 320, 51, 51))
        self.n5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n5.setAutoFillBackground(False)
        self.n5.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n5.setAlignment(QtCore.Qt.AlignCenter)
        self.n5.setObjectName("n5")
        self.n4 = QtWidgets.QLabel(self.Time_pro)
        self.n4.setGeometry(QtCore.QRect(430, 320, 51, 51))
        self.n4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n4.setAutoFillBackground(False)
        self.n4.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n4.setAlignment(QtCore.Qt.AlignCenter)
        self.n4.setObjectName("n4")
        self.n7 = QtWidgets.QLabel(self.Time_pro)
        self.n7.setGeometry(QtCore.QRect(610, 320, 51, 51))
        self.n7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n7.setAutoFillBackground(False)
        self.n7.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n7.setAlignment(QtCore.Qt.AlignCenter)
        self.n7.setObjectName("n7")
        self.n6 = QtWidgets.QLabel(self.Time_pro)
        self.n6.setGeometry(QtCore.QRect(550, 320, 51, 51))
        self.n6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n6.setAutoFillBackground(False)
        self.n6.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n6.setAlignment(QtCore.Qt.AlignCenter)
        self.n6.setObjectName("n6")
        self.n9 = QtWidgets.QLabel(self.Time_pro)
        self.n9.setGeometry(QtCore.QRect(730, 320, 51, 51))
        self.n9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n9.setAutoFillBackground(False)
        self.n9.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n9.setAlignment(QtCore.Qt.AlignCenter)
        self.n9.setObjectName("n9")
        self.n8 = QtWidgets.QLabel(self.Time_pro)
        self.n8.setGeometry(QtCore.QRect(670, 320, 51, 51))
        self.n8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n8.setAutoFillBackground(False)
        self.n8.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n8.setAlignment(QtCore.Qt.AlignCenter)
        self.n8.setObjectName("n8")
        self.n0 = QtWidgets.QLabel(self.Time_pro)
        self.n0.setGeometry(QtCore.QRect(790, 320, 51, 51))
        self.n0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n0.setAutoFillBackground(False)
        self.n0.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n0.setAlignment(QtCore.Qt.AlignCenter)
        self.n0.setObjectName("n0")
        self.eq = QtWidgets.QLabel(self.Time_pro)
        self.eq.setGeometry(QtCore.QRect(910, 320, 51, 51))
        self.eq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.eq.setAutoFillBackground(False)
        self.eq.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.eq.setAlignment(QtCore.Qt.AlignCenter)
        self.eq.setObjectName("eq")
        self.dash = QtWidgets.QLabel(self.Time_pro)
        self.dash.setGeometry(QtCore.QRect(850, 320, 51, 51))
        self.dash.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dash.setAutoFillBackground(False)
        self.dash.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.dash.setAlignment(QtCore.Qt.AlignCenter)
        self.dash.setObjectName("dash")
        self.tab = QtWidgets.QLabel(self.Time_pro)
        self.tab.setGeometry(QtCore.QRect(190, 380, 71, 51))
        self.tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab.setAutoFillBackground(False)
        self.tab.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.tab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tab.setObjectName("tab")
        self.caps = QtWidgets.QLabel(self.Time_pro)
        self.caps.setGeometry(QtCore.QRect(190, 440, 101, 51))
        self.caps.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.caps.setAutoFillBackground(False)
        self.caps.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.caps.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.caps.setIndent(10)
        self.caps.setObjectName("caps")
        self.ctrl_l = QtWidgets.QLabel(self.Time_pro)
        self.ctrl_l.setGeometry(QtCore.QRect(190, 560, 71, 51))
        self.ctrl_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ctrl_l.setAutoFillBackground(False)
        self.ctrl_l.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.ctrl_l.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_l.setObjectName("ctrl_l")
        self.shift_r = QtWidgets.QLabel(self.Time_pro)
        self.shift_r.setGeometry(QtCore.QRect(190, 500, 141, 51))
        self.shift_r.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shift_r.setAutoFillBackground(False)
        self.shift_r.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.shift_r.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shift_r.setIndent(10)
        self.shift_r.setObjectName("shift_r")
        self.let1_2 = QtWidgets.QLabel(self.Time_pro)
        self.let1_2.setGeometry(QtCore.QRect(330, 380, 51, 51))
        self.let1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_2.setAutoFillBackground(False)
        self.let1_2.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_2.setObjectName("let1_2")
        self.let2_2 = QtWidgets.QLabel(self.Time_pro)
        self.let2_2.setGeometry(QtCore.QRect(360, 440, 51, 51))
        self.let2_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_2.setAutoFillBackground(False)
        self.let2_2.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_2.setObjectName("let2_2")
        self.let1_4 = QtWidgets.QLabel(self.Time_pro)
        self.let1_4.setGeometry(QtCore.QRect(450, 380, 51, 51))
        self.let1_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_4.setAutoFillBackground(False)
        self.let1_4.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_4.setObjectName("let1_4")
        self.let1_3 = QtWidgets.QLabel(self.Time_pro)
        self.let1_3.setGeometry(QtCore.QRect(390, 380, 51, 51))
        self.let1_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_3.setAutoFillBackground(False)
        self.let1_3.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_3.setObjectName("let1_3")
        self.let3_2 = QtWidgets.QLabel(self.Time_pro)
        self.let3_2.setGeometry(QtCore.QRect(400, 500, 51, 51))
        self.let3_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_2.setAutoFillBackground(False)
        self.let3_2.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_2.setObjectName("let3_2")
        self.let1_5 = QtWidgets.QLabel(self.Time_pro)
        self.let1_5.setGeometry(QtCore.QRect(510, 380, 51, 51))
        self.let1_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_5.setAutoFillBackground(False)
        self.let1_5.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_5.setObjectName("let1_5")
        self.let1_6 = QtWidgets.QLabel(self.Time_pro)
        self.let1_6.setGeometry(QtCore.QRect(570, 380, 51, 51))
        self.let1_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_6.setAutoFillBackground(False)
        self.let1_6.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_6.setObjectName("let1_6")
        self.let1_7 = QtWidgets.QLabel(self.Time_pro)
        self.let1_7.setGeometry(QtCore.QRect(630, 380, 51, 51))
        self.let1_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_7.setAutoFillBackground(False)
        self.let1_7.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_7.setObjectName("let1_7")
        self.let1_8 = QtWidgets.QLabel(self.Time_pro)
        self.let1_8.setGeometry(QtCore.QRect(690, 380, 51, 51))
        self.let1_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_8.setAutoFillBackground(False)
        self.let1_8.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_8.setObjectName("let1_8")
        self.let1_10 = QtWidgets.QLabel(self.Time_pro)
        self.let1_10.setGeometry(QtCore.QRect(810, 380, 51, 51))
        self.let1_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_10.setAutoFillBackground(False)
        self.let1_10.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_10.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_10.setObjectName("let1_10")
        self.let1_9 = QtWidgets.QLabel(self.Time_pro)
        self.let1_9.setGeometry(QtCore.QRect(750, 380, 51, 51))
        self.let1_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_9.setAutoFillBackground(False)
        self.let1_9.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_9.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_9.setObjectName("let1_9")
        self.let1_12 = QtWidgets.QLabel(self.Time_pro)
        self.let1_12.setGeometry(QtCore.QRect(930, 380, 51, 51))
        self.let1_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_12.setAutoFillBackground(False)
        self.let1_12.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_12.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_12.setObjectName("let1_12")
        self.let1_11 = QtWidgets.QLabel(self.Time_pro)
        self.let1_11.setGeometry(QtCore.QRect(870, 380, 51, 51))
        self.let1_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_11.setAutoFillBackground(False)
        self.let1_11.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_11.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_11.setObjectName("let1_11")
        self.let2_6 = QtWidgets.QLabel(self.Time_pro)
        self.let2_6.setGeometry(QtCore.QRect(600, 440, 51, 51))
        self.let2_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_6.setAutoFillBackground(False)
        self.let2_6.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_6.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_6.setObjectName("let2_6")
        self.let2_5 = QtWidgets.QLabel(self.Time_pro)
        self.let2_5.setGeometry(QtCore.QRect(540, 440, 51, 51))
        self.let2_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_5.setAutoFillBackground(False)
        self.let2_5.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_5.setObjectName("let2_5")
        self.let2_9 = QtWidgets.QLabel(self.Time_pro)
        self.let2_9.setGeometry(QtCore.QRect(780, 440, 51, 51))
        self.let2_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_9.setAutoFillBackground(False)
        self.let2_9.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_9.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_9.setObjectName("let2_9")
        self.let2_8 = QtWidgets.QLabel(self.Time_pro)
        self.let2_8.setGeometry(QtCore.QRect(720, 440, 51, 51))
        self.let2_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_8.setAutoFillBackground(False)
        self.let2_8.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_8.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_8.setObjectName("let2_8")
        self.let2_4 = QtWidgets.QLabel(self.Time_pro)
        self.let2_4.setGeometry(QtCore.QRect(480, 440, 51, 51))
        self.let2_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_4.setAutoFillBackground(False)
        self.let2_4.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_4.setObjectName("let2_4")
        self.let2_3 = QtWidgets.QLabel(self.Time_pro)
        self.let2_3.setGeometry(QtCore.QRect(420, 440, 51, 51))
        self.let2_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_3.setAutoFillBackground(False)
        self.let2_3.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_3.setObjectName("let2_3")
        self.let2_11 = QtWidgets.QLabel(self.Time_pro)
        self.let2_11.setGeometry(QtCore.QRect(900, 440, 51, 51))
        self.let2_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_11.setAutoFillBackground(False)
        self.let2_11.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_11.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_11.setObjectName("let2_11")
        self.let2_10 = QtWidgets.QLabel(self.Time_pro)
        self.let2_10.setGeometry(QtCore.QRect(840, 440, 51, 51))
        self.let2_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_10.setAutoFillBackground(False)
        self.let2_10.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_10.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_10.setObjectName("let2_10")
        self.let2_7 = QtWidgets.QLabel(self.Time_pro)
        self.let2_7.setGeometry(QtCore.QRect(660, 440, 51, 51))
        self.let2_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_7.setAutoFillBackground(False)
        self.let2_7.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_7.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_7.setObjectName("let2_7")
        self.let3_4 = QtWidgets.QLabel(self.Time_pro)
        self.let3_4.setGeometry(QtCore.QRect(520, 500, 51, 51))
        self.let3_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_4.setAutoFillBackground(False)
        self.let3_4.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_4.setObjectName("let3_4")
        self.let3_6 = QtWidgets.QLabel(self.Time_pro)
        self.let3_6.setGeometry(QtCore.QRect(640, 500, 51, 51))
        self.let3_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_6.setAutoFillBackground(False)
        self.let3_6.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_6.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_6.setObjectName("let3_6")
        self.let3_7 = QtWidgets.QLabel(self.Time_pro)
        self.let3_7.setGeometry(QtCore.QRect(700, 500, 51, 51))
        self.let3_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_7.setAutoFillBackground(False)
        self.let3_7.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_7.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_7.setObjectName("let3_7")
        self.let3_9 = QtWidgets.QLabel(self.Time_pro)
        self.let3_9.setGeometry(QtCore.QRect(820, 500, 51, 51))
        self.let3_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_9.setAutoFillBackground(False)
        self.let3_9.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_9.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_9.setObjectName("let3_9")
        self.let3_8 = QtWidgets.QLabel(self.Time_pro)
        self.let3_8.setGeometry(QtCore.QRect(760, 500, 51, 51))
        self.let3_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_8.setAutoFillBackground(False)
        self.let3_8.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_8.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_8.setObjectName("let3_8")
        self.let3_5 = QtWidgets.QLabel(self.Time_pro)
        self.let3_5.setGeometry(QtCore.QRect(580, 500, 51, 51))
        self.let3_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_5.setAutoFillBackground(False)
        self.let3_5.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_5.setObjectName("let3_5")
        self.let3_3 = QtWidgets.QLabel(self.Time_pro)
        self.let3_3.setGeometry(QtCore.QRect(460, 500, 51, 51))
        self.let3_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_3.setAutoFillBackground(False)
        self.let3_3.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_3.setObjectName("let3_3")
        self.let3_10 = QtWidgets.QLabel(self.Time_pro)
        self.let3_10.setGeometry(QtCore.QRect(880, 500, 51, 51))
        self.let3_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_10.setAutoFillBackground(False)
        self.let3_10.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_10.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_10.setObjectName("let3_10")
        self.win_l = QtWidgets.QLabel(self.Time_pro)
        self.win_l.setGeometry(QtCore.QRect(270, 560, 61, 51))
        self.win_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.win_l.setAutoFillBackground(False)
        self.win_l.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.win_l.setAlignment(QtCore.Qt.AlignCenter)
        self.win_l.setObjectName("win_l")
        self.alt_l = QtWidgets.QLabel(self.Time_pro)
        self.alt_l.setGeometry(QtCore.QRect(340, 560, 61, 51))
        self.alt_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.alt_l.setAutoFillBackground(False)
        self.alt_l.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.alt_l.setAlignment(QtCore.Qt.AlignCenter)
        self.alt_l.setObjectName("alt_l")
        self.space = QtWidgets.QLabel(self.Time_pro)
        self.space.setGeometry(QtCore.QRect(410, 560, 391, 51))
        self.space.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.space.setAutoFillBackground(False)
        self.space.setStyleSheet("background-color: rgb(175, 175, 225);\n"
"font: 10pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.space.setText("")
        self.space.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.space.setObjectName("space")
        self.win_r = QtWidgets.QLabel(self.Time_pro)
        self.win_r.setGeometry(QtCore.QRect(880, 560, 61, 51))
        self.win_r.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.win_r.setAutoFillBackground(False)
        self.win_r.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.win_r.setAlignment(QtCore.Qt.AlignCenter)
        self.win_r.setObjectName("win_r")
        self.ctrl_r = QtWidgets.QLabel(self.Time_pro)
        self.ctrl_r.setGeometry(QtCore.QRect(1020, 560, 61, 51))
        self.ctrl_r.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ctrl_r.setAutoFillBackground(False)
        self.ctrl_r.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.ctrl_r.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_r.setObjectName("ctrl_r")
        self.alt_r = QtWidgets.QLabel(self.Time_pro)
        self.alt_r.setGeometry(QtCore.QRect(810, 560, 61, 51))
        self.alt_r.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.alt_r.setAutoFillBackground(False)
        self.alt_r.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.alt_r.setAlignment(QtCore.Qt.AlignCenter)
        self.alt_r.setObjectName("alt_r")
        self.menu = QtWidgets.QLabel(self.Time_pro)
        self.menu.setGeometry(QtCore.QRect(950, 560, 61, 51))
        self.menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu.setAutoFillBackground(False)
        self.menu.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.menu.setAlignment(QtCore.Qt.AlignCenter)
        self.menu.setObjectName("menu")
        self.backspace = QtWidgets.QLabel(self.Time_pro)
        self.backspace.setGeometry(QtCore.QRect(970, 320, 111, 51))
        self.backspace.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.backspace.setAutoFillBackground(False)
        self.backspace.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.backspace.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.backspace.setIndent(10)
        self.backspace.setObjectName("backspace")
        self.slash = QtWidgets.QLabel(self.Time_pro)
        self.slash.setGeometry(QtCore.QRect(990, 380, 91, 51))
        self.slash.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slash.setAutoFillBackground(False)
        self.slash.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.slash.setAlignment(QtCore.Qt.AlignCenter)
        self.slash.setObjectName("slash")
        self.enter = QtWidgets.QLabel(self.Time_pro)
        self.enter.setGeometry(QtCore.QRect(960, 440, 121, 51))
        self.enter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enter.setAutoFillBackground(False)
        self.enter.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.enter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.enter.setIndent(10)
        self.enter.setObjectName("enter")
        self.shift_l = QtWidgets.QLabel(self.Time_pro)
        self.shift_l.setGeometry(QtCore.QRect(940, 500, 141, 51))
        self.shift_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shift_l.setAutoFillBackground(False)
        self.shift_l.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.shift_l.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shift_l.setIndent(10)
        self.shift_l.setObjectName("shift_l")
        self.bg = QtWidgets.QLabel(self.Time_pro)
        self.bg.setGeometry(QtCore.QRect(170, 300, 931, 331))
        self.bg.setStyleSheet("background-color: rgb(153, 180, 209);\n"
"border-radius: 5px;")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.bg.raise_()
        self.text.raise_()
        self.yo.raise_()
        self.let1_1.raise_()
        self.n2.raise_()
        self.n1.raise_()
        self.let2_1.raise_()
        self.let3_1.raise_()
        self.n3.raise_()
        self.n5.raise_()
        self.n4.raise_()
        self.n7.raise_()
        self.n6.raise_()
        self.n9.raise_()
        self.n8.raise_()
        self.n0.raise_()
        self.eq.raise_()
        self.dash.raise_()
        self.tab.raise_()
        self.caps.raise_()
        self.ctrl_l.raise_()
        self.shift_r.raise_()
        self.let1_2.raise_()
        self.let2_2.raise_()
        self.let1_4.raise_()
        self.let1_3.raise_()
        self.let3_2.raise_()
        self.let1_5.raise_()
        self.let1_6.raise_()
        self.let1_7.raise_()
        self.let1_8.raise_()
        self.let1_10.raise_()
        self.let1_9.raise_()
        self.let1_12.raise_()
        self.let1_11.raise_()
        self.let2_6.raise_()
        self.let2_5.raise_()
        self.let2_9.raise_()
        self.let2_8.raise_()
        self.let2_4.raise_()
        self.let2_3.raise_()
        self.let2_11.raise_()
        self.let2_10.raise_()
        self.let2_7.raise_()
        self.let3_4.raise_()
        self.let3_6.raise_()
        self.let3_7.raise_()
        self.let3_9.raise_()
        self.let3_8.raise_()
        self.let3_5.raise_()
        self.let3_3.raise_()
        self.let3_10.raise_()
        self.win_l.raise_()
        self.alt_l.raise_()
        self.space.raise_()
        self.win_r.raise_()
        self.ctrl_r.raise_()
        self.alt_r.raise_()
        self.menu.raise_()
        self.backspace.raise_()
        self.slash.raise_()
        self.enter.raise_()
        self.shift_l.raise_()
        self.stackedWidget.addWidget(self.Time_pro)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text.setText(_translate("MainWindow", "Просто текст"))
        self.yo.setText(_translate("MainWindow", "ё"))
        self.let1_1.setText(_translate("MainWindow", "й"))
        self.n2.setText(_translate("MainWindow", "2"))
        self.n1.setText(_translate("MainWindow", "1"))
        self.let2_1.setText(_translate("MainWindow", "ф"))
        self.let3_1.setText(_translate("MainWindow", "я"))
        self.n3.setText(_translate("MainWindow", "3"))
        self.n5.setText(_translate("MainWindow", "5"))
        self.n4.setText(_translate("MainWindow", "4"))
        self.n7.setText(_translate("MainWindow", "7"))
        self.n6.setText(_translate("MainWindow", "6"))
        self.n9.setText(_translate("MainWindow", "9"))
        self.n8.setText(_translate("MainWindow", "8"))
        self.n0.setText(_translate("MainWindow", "0"))
        self.eq.setText(_translate("MainWindow", "="))
        self.dash.setText(_translate("MainWindow", "-"))
        self.tab.setText(_translate("MainWindow", "Tab"))
        self.caps.setText(_translate("MainWindow", "Caps Lock"))
        self.ctrl_l.setText(_translate("MainWindow", "Ctrl"))
        self.shift_r.setText(_translate("MainWindow", "Shift"))
        self.let1_2.setText(_translate("MainWindow", "ц"))
        self.let2_2.setText(_translate("MainWindow", "ы"))
        self.let1_4.setText(_translate("MainWindow", "к"))
        self.let1_3.setText(_translate("MainWindow", "у"))
        self.let3_2.setText(_translate("MainWindow", "ч"))
        self.let1_5.setText(_translate("MainWindow", "е"))
        self.let1_6.setText(_translate("MainWindow", "н"))
        self.let1_7.setText(_translate("MainWindow", "г"))
        self.let1_8.setText(_translate("MainWindow", "ш"))
        self.let1_10.setText(_translate("MainWindow", "з"))
        self.let1_9.setText(_translate("MainWindow", "щ"))
        self.let1_12.setText(_translate("MainWindow", "ъ"))
        self.let1_11.setText(_translate("MainWindow", "х"))
        self.let2_6.setText(_translate("MainWindow", "р"))
        self.let2_5.setText(_translate("MainWindow", "п"))
        self.let2_9.setText(_translate("MainWindow", "д"))
        self.let2_8.setText(_translate("MainWindow", "л"))
        self.let2_4.setText(_translate("MainWindow", "а"))
        self.let2_3.setText(_translate("MainWindow", "в"))
        self.let2_11.setText(_translate("MainWindow", "э"))
        self.let2_10.setText(_translate("MainWindow", "ж"))
        self.let2_7.setText(_translate("MainWindow", "о"))
        self.let3_4.setText(_translate("MainWindow", "м"))
        self.let3_6.setText(_translate("MainWindow", "т"))
        self.let3_7.setText(_translate("MainWindow", "ь"))
        self.let3_9.setText(_translate("MainWindow", "ю"))
        self.let3_8.setText(_translate("MainWindow", "б"))
        self.let3_5.setText(_translate("MainWindow", "и"))
        self.let3_3.setText(_translate("MainWindow", "с"))
        self.let3_10.setText(_translate("MainWindow", "."))
        self.win_l.setText(_translate("MainWindow", "Win"))
        self.alt_l.setText(_translate("MainWindow", "Alt"))
        self.win_r.setText(_translate("MainWindow", "Win"))
        self.ctrl_r.setText(_translate("MainWindow", "Ctrl"))
        self.alt_r.setText(_translate("MainWindow", "Alt"))
        self.menu.setText(_translate("MainWindow", "Menu"))
        self.backspace.setText(_translate("MainWindow", "Backspace"))
        self.slash.setText(_translate("MainWindow", "\\"))
        self.enter.setText(_translate("MainWindow", "Enter"))
        self.shift_l.setText(_translate("MainWindow", "Shift"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
